# Generated by Django 4.2.7 on 2025-12-03 15:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colleague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(blank=True, max_length=20)),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full-time equivalent (0.1 to 1.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed-term", "Fixed Term"),
                            ("research", "Research Only"),
                        ],
                        default="permanent",
                        max_length=50,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("current", "Current Staff"),
                            ("former", "Former Staff"),
                        ],
                        default="current",
                        help_text="Whether this person is currently employed or a former staff member",
                        max_length=10,
                    ),
                ),
                (
                    "employment_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when employment ended (for former staff)",
                        null=True,
                    ),
                ),
                (
                    "colleague_category",
                    models.CharField(
                        choices=[
                            ("independent", "Independent Researcher"),
                            ("non_independent", "Non Independent Researcher"),
                            ("postdoc", "Post-Doctoral Researcher"),
                            ("research_assistant", "Research Assistant"),
                            ("academic", "Academic Staff"),
                            ("support", "Support Staff"),
                            ("employee", "Current Employee"),
                            ("former", "Former Employee"),
                            ("coauthor", "Co-author (External)"),
                        ],
                        default="independent",
                        help_text="Category of colleague for REF purposes",
                        max_length=50,
                        verbose_name="Colleague Category",
                    ),
                ),
                ("unit_of_assessment", models.CharField(max_length=100)),
                ("is_returnable", models.BooleanField(default=True)),
                ("submission_group", models.CharField(blank=True, max_length=100)),
                ("office", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="CriticalFriend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "expertise_areas",
                    models.TextField(
                        help_text="Research areas and expertise (comma-separated)"
                    ),
                ),
                ("research_interests", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("orcid", models.CharField(blank=True, max_length=50)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("limited", "Limited Availability"),
                            ("unavailable", "Currently Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "max_assignments",
                    models.IntegerField(
                        default=5, help_text="Maximum concurrent review assignments"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Critical Friend",
                "verbose_name_plural": "Critical Friends",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("A", "Journal Article"),
                            ("B", "Book"),
                            ("C", "Book Chapter"),
                            ("D", "Conference Paper"),
                            ("E", "Patent"),
                            ("F", "Software"),
                            ("G", "Performance/Exhibition"),
                            ("H", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        help_text="Year of publication (e.g., 2024)",
                        validators=[
                            django.core.validators.MinValueValidator(2021),
                            django.core.validators.MaxValueValidator(2028),
                        ],
                    ),
                ),
                ("publication_venue", models.CharField(blank=True, max_length=300)),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("issue", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("doi", models.CharField(blank=True, max_length=200)),
                ("isbn", models.CharField(blank=True, max_length=50)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "all_authors",
                    models.TextField(help_text="All authors in citation format"),
                ),
                (
                    "author_position",
                    models.IntegerField(
                        help_text="Position of colleague in author list",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "uoa",
                    models.CharField(max_length=100, verbose_name="Unit of Assessment"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("internal-review", "Internal Review"),
                            ("external-review", "External Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision", "Needs Revision"),
                            ("aside", "Set aside for now"),
                            ("planning", "In Planning"),
                            ("ready", "Ready to Submit"),
                            ("reserve", "Reserve"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "quality_rating_internal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        help_text="Quality assessment from internal panel",
                        max_length=2,
                        verbose_name="Internal Panel Rating",
                    ),
                ),
                (
                    "quality_rating_external",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        help_text="Quality assessment from critical friends",
                        max_length=2,
                        verbose_name="Critical Friend Rating",
                    ),
                ),
                (
                    "quality_rating_self",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        help_text="Author's own quality assessment",
                        max_length=2,
                        verbose_name="Self-Assessment Rating",
                    ),
                ),
                (
                    "quality_rating_average",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        help_text="Calculated average of internal and external ratings",
                        max_length=2,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "quality_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        max_length=2,
                        verbose_name="Overall Rating (Deprecated)",
                    ),
                ),
                (
                    "originality_self",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Self-assessment of originality (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Originality (Self)",
                    ),
                ),
                (
                    "significance_self",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Self-assessment of significance (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Significance (Self)",
                    ),
                ),
                (
                    "rigour_self",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Self-assessment of rigour (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Rigour (Self)",
                    ),
                ),
                (
                    "originality_internal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal panel rating for originality (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Originality (Internal)",
                    ),
                ),
                (
                    "significance_internal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal panel rating for significance (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Significance (Internal)",
                    ),
                ),
                (
                    "rigour_internal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal panel rating for rigour (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Rigour (Internal)",
                    ),
                ),
                (
                    "originality_external",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Critical friend rating for originality (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Originality (External)",
                    ),
                ),
                (
                    "significance_external",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Critical friend rating for significance (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Significance (External)",
                    ),
                ),
                (
                    "rigour_external",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Critical friend rating for rigour (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                        verbose_name="Rigour (External)",
                    ),
                ),
                ("is_double_weighted", models.BooleanField(default=False)),
                ("is_interdisciplinary", models.BooleanField(default=False)),
                ("is_open_access", models.BooleanField(default=False)),
                (
                    "acceptance_date",
                    models.DateField(
                        blank=True,
                        help_text="Date paper was accepted for publication. Critical for 3-month deposit rule verification.",
                        null=True,
                        verbose_name="Acceptance Date",
                    ),
                ),
                (
                    "deposit_date",
                    models.DateField(
                        blank=True,
                        help_text="Date uploaded to institutional repository (e.g., YORA).",
                        null=True,
                        verbose_name="Repository Deposit Date",
                    ),
                ),
                (
                    "embargo_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when full-text access becomes publicly available.",
                        null=True,
                        verbose_name="Embargo End Date",
                    ),
                ),
                (
                    "oa_status",
                    models.CharField(
                        choices=[
                            ("gold", "Gold Open Access (Journal-hosted, paid APC)"),
                            ("green", "Green Open Access (Repository, e.g., YORA)"),
                            ("hybrid", "Hybrid (Subscription journal + OA option)"),
                            ("bronze", "Bronze (Free to read, no formal license)"),
                            ("closed", "Closed / Paywalled"),
                            ("non_compliant", "Non-Compliant with REF OA Policy"),
                        ],
                        default="closed",
                        help_text="Detailed Open Access status for REF compliance reporting.",
                        max_length=20,
                        verbose_name="Open Access Status",
                    ),
                ),
                (
                    "oa_exception",
                    models.CharField(
                        choices=[
                            ("none", "No Exception Required"),
                            (
                                "deposit",
                                "Deposit Exception (Technical/Personal barrier)",
                            ),
                            ("access", "Access Exception (Publisher embargo)"),
                            ("technical", "Technical Exception"),
                            ("gold_route", "Gold Route Exception"),
                            ("other", "Other (See compliance notes)"),
                        ],
                        default="none",
                        help_text="Exception type if output does not meet standard OA requirements.",
                        max_length=20,
                        verbose_name="OA Exception Type",
                    ),
                ),
                (
                    "double_weighting_statement",
                    models.TextField(
                        blank=True,
                        help_text="Required if Double Weighted. Max 300 words explaining why this output merits extended scope/scale weighting.",
                        verbose_name="Double Weighting Statement",
                    ),
                ),
                (
                    "interdisciplinary_statement",
                    models.TextField(
                        blank=True,
                        help_text="Explain the interdisciplinary methodology, contribution, and cross-panel value.",
                        verbose_name="Interdisciplinary Statement",
                    ),
                ),
                (
                    "citation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Citation count from OpenAlex/Crossref. Auto-updated on DOI fetch.",
                        verbose_name="Citation Count",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="outputs/"),
                ),
                (
                    "supplementary_file",
                    models.FileField(
                        blank=True, null=True, upload_to="outputs/supplementary/"
                    ),
                ),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("internal_notes", models.TextField(blank=True)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Risk of panel disagreement with methodology/approach (0-1 scale)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "content_risk_rationale",
                    models.TextField(
                        blank=True,
                        help_text="Explain why this output might face panel disagreement or concerns",
                    ),
                ),
                (
                    "timeline_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Risk of publication delay (0=published, 1=planning stage)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "overall_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated composite risk score",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "risk_content_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.60"),
                        help_text="Weight for content risk (default 0.6)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "risk_timeline_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.40"),
                        help_text="Weight for timeline risk (default 0.4)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "oa_compliance_risk",
                    models.BooleanField(
                        default=False,
                        help_text="Is there Open Access compliance risk? (Critical for REF)",
                    ),
                ),
                (
                    "oa_compliance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Details about OA compliance status or concerns",
                    ),
                ),
                (
                    "panel_alignment_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="How well does this align with panel expertise? (1=perfect, 0=poor)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "panel_alignment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on panel alignment concerns or alternative UOA considerations",
                    ),
                ),
                (
                    "venue_prestige_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Journal/venue prestige and reputation (0=low, 1=high)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "interdisciplinary_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Is this interdisciplinary work? (May receive additional weighting)",
                    ),
                ),
                (
                    "risk_last_calculated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When risk scores were last calculated",
                        null=True,
                    ),
                ),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="core.colleague",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="REFSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "uoa",
                    models.CharField(max_length=100, verbose_name="Unit of Assessment"),
                ),
                (
                    "submission_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2025),
                            django.core.validators.MaxValueValidator(2035),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("submitted", "Submitted"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "portfolio_quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average quality score of included outputs (0-4 scale)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                (
                    "portfolio_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average risk score of included outputs (0-1 scale)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "representativeness_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="How well outputs represent staff research (0-1 scale)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "equality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="EDI metric for submission balance",
                        max_digits=5,
                    ),
                ),
                (
                    "gender_balance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gender balance metric (0.5 = perfect balance)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "ecr_representation_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Early Career Researcher representation",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "interdisciplinary_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Proportion of interdisciplinary outputs",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "weight_quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Weight for quality in overall score",
                        max_digits=3,
                    ),
                ),
                (
                    "weight_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.20"),
                        help_text="Weight for risk in overall score",
                        max_digits=3,
                    ),
                ),
                (
                    "weight_representativeness",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Weight for representativeness",
                        max_digits=3,
                    ),
                ),
                (
                    "weight_equality",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Weight for equality metrics",
                        max_digits=3,
                    ),
                ),
                (
                    "weight_gender_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Weight for gender balance",
                        max_digits=3,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metrics_last_calculated",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "REF Submission",
                "verbose_name_plural": "REF Submissions",
                "ordering": ["-submission_year", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("OBSERVER", "Observer (Read-Only)"),
                            ("INTERNAL_PANEL", "Internal Panel Member"),
                            ("COLLEAGUE", "Colleague"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "can_view_all_outputs",
                    models.BooleanField(
                        default=False, help_text="Can view all outputs in the system"
                    ),
                ),
                (
                    "can_view_all_colleagues",
                    models.BooleanField(
                        default=False, help_text="Can view all colleague records"
                    ),
                ),
                (
                    "can_view_all_ratings",
                    models.BooleanField(
                        default=False, help_text="Can view all internal ratings"
                    ),
                ),
                (
                    "can_edit_any_output",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit any output regardless of ownership",
                    ),
                ),
                (
                    "can_delete_any_output",
                    models.BooleanField(
                        default=False, help_text="Can delete any output"
                    ),
                ),
                (
                    "can_edit_any_rating",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit any rating including finalised ones",
                    ),
                ),
                (
                    "can_create_outputs",
                    models.BooleanField(
                        default=False, help_text="Can create new outputs"
                    ),
                ),
                (
                    "can_rate_assigned",
                    models.BooleanField(
                        default=False,
                        help_text="Can rate outputs assigned to this user",
                    ),
                ),
                (
                    "can_unfinalise_ratings",
                    models.BooleanField(
                        default=False,
                        help_text="Can un-finalise ratings that have been locked",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, help_text="Can manage user accounts and roles"
                    ),
                ),
                (
                    "can_assign_panel",
                    models.BooleanField(
                        default=False, help_text="Can assign outputs to panel members"
                    ),
                ),
                (
                    "can_export_data",
                    models.BooleanField(
                        default=False, help_text="Can export data from the system"
                    ),
                ),
                (
                    "can_import_data",
                    models.BooleanField(
                        default=False, help_text="Can import data into the system"
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linked_colleague",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Colleague record for this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="core.colleague",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User can have multiple roles. Permissions are combined.",
                        related_name="users",
                        to="core.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data_collection", "Data Collection"),
                            ("review", "Output Review"),
                            ("compliance", "Compliance Check"),
                            ("communication", "Communication"),
                            ("documentation", "Documentation"),
                            ("training", "Training"),
                            ("reporting", "Reporting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-priority", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within submission"
                    ),
                ),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes specific to this output's inclusion in this submission",
                    ),
                ),
                (
                    "is_reserve",
                    models.BooleanField(
                        default=False, help_text="Is this a reserve/backup output?"
                    ),
                ),
                (
                    "strategic_importance",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("important", "Important"),
                            ("standard", "Standard"),
                            ("optional", "Optional"),
                        ],
                        default="standard",
                        help_text="Strategic importance of this output to the submission",
                        max_length=20,
                    ),
                ),
                ("included_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_inclusions",
                        to="core.output",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_outputs",
                        to="core.refsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Output",
                "verbose_name_plural": "Submission Outputs",
                "ordering": ["order", "included_date"],
                "unique_together": {("submission", "output")},
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_entity",
                    models.CharField(
                        help_text="Who is the request from?", max_length=200
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="refsubmission",
            name="outputs",
            field=models.ManyToManyField(
                related_name="ref_submissions",
                through="core.SubmissionOutput",
                to="core.output",
            ),
        ),
        migrations.CreateModel(
            name="InternalPanelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "Panel Chair"),
                            ("deputy", "Deputy Chair"),
                            ("member", "Panel Member"),
                            ("observer", "Observer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("expertise_area", models.CharField(blank=True, max_length=200)),
                ("appointed_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_memberships",
                        to="core.colleague",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Panel Member",
                "verbose_name_plural": "Internal Panel Members",
                "ordering": ["colleague__user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="PanelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_assignments",
                        to="core.output",
                    ),
                ),
                (
                    "panel_member",
                    models.ForeignKey(
                        limit_choices_to={"roles__code": "INTERNAL_PANEL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel Assignment",
                "verbose_name_plural": "Panel Assignments",
                "ordering": ["-assigned_date"],
                "unique_together": {("output", "panel_member")},
            },
        ),
        migrations.CreateModel(
            name="InternalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_reviews",
                        to="core.output",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("output", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="InternalRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Not Rated"),
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Justification and notes for this rating"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Once finalised, only admins can modify",
                    ),
                ),
                (
                    "finalised_date",
                    models.DateTimeField(
                        blank=True, help_text="When the rating was finalised", null=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_ratings",
                        to="core.output",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Rating",
                "verbose_name_plural": "Internal Ratings",
                "ordering": ["-created_date"],
                "unique_together": {("output", "rater")},
            },
        ),
        migrations.CreateModel(
            name="InternalPanelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewer_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead Reviewer"),
                            ("second", "Second Reviewer"),
                            ("specialist", "Specialist"),
                            ("general", "General Reviewer"),
                        ],
                        default="general",
                        help_text="Classification of reviewer expertise for this output",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "rating_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        help_text="Recommended quality rating",
                        max_length=2,
                    ),
                ),
                (
                    "originality_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Originality rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                (
                    "significance_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Significance rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                (
                    "rigour_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rigour rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "confidential_comments",
                    models.TextField(
                        blank=True,
                        help_text="Comments visible only to admin and other panel members",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_panel_assignments",
                        to="core.output",
                    ),
                ),
                (
                    "panel_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_assignments",
                        to="core.internalpanelmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Panel Assignment",
                "verbose_name_plural": "Internal Panel Assignments",
                "ordering": ["-assigned_date"],
                "unique_together": {("output", "panel_member")},
            },
        ),
        migrations.CreateModel(
            name="CriticalFriendAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "quality_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "originality_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Originality rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                (
                    "significance_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Significance rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                (
                    "rigour_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rigour rating (0.00-4.00)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("4.00")),
                        ],
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("overall_comments", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "critical_friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.criticalfriend",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_friend_reviews",
                        to="core.output",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
                "unique_together": {("output", "critical_friend")},
            },
        ),
    ]
