# Generated by Django 4.2.7 on 2025-10-21 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('fte', models.DecimalField(decimal_places=2, help_text='Full-time equivalent (0.1 to 1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed-term', 'Fixed Term'), ('research', 'Research Only')], default='permanent', max_length=50)),
                ('unit_of_assessment', models.CharField(max_length=100)),
                ('is_returnable', models.BooleanField(default=True)),
                ('submission_group', models.CharField(blank=True, max_length=100)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CriticalFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('institution', models.CharField(max_length=300)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('expertise_areas', models.TextField(help_text='Comma-separated list')),
                ('research_interests', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('busy', 'Currently Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('max_assignments', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_friend_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entity', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_type', models.CharField(choices=[('A', 'Journal Article'), ('B', 'Book'), ('C', 'Book Chapter'), ('D', 'Conference Paper'), ('E', 'Patent'), ('F', 'Software'), ('G', 'Performance/Exhibition'), ('H', 'Other')], max_length=1)),
                ('publication_date', models.DateField()),
                ('publication_venue', models.CharField(blank=True, max_length=300)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('all_authors', models.TextField(help_text='All authors in citation format')),
                ('author_position', models.IntegerField(help_text='Position of colleague in author list', validators=[django.core.validators.MinValueValidator(1)])),
                ('uoa', models.CharField(max_length=100, verbose_name='Unit of Assessment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('internal-review', 'Internal Review'), ('external-review', 'External Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Needs Revision')], default='draft', max_length=20)),
                ('quality_rating', models.CharField(blank=True, choices=[('4*', '4* - World-leading'), ('3*', '3* - Internationally excellent'), ('2*', '2* - Recognized internationally'), ('1*', '1* - Recognized nationally'), ('U', 'Unclassified')], help_text='Internal quality assessment', max_length=2)),
                ('is_double_weighted', models.BooleanField(default=False)),
                ('is_interdisciplinary', models.BooleanField(default=False)),
                ('is_open_access', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('supplementary_file', models.FileField(blank=True, null=True, upload_to='outputs/supplementary/')),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.colleague')),
            ],
            options={
                'verbose_name_plural': 'Outputs',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_assessment', models.CharField(choices=[('4*', '4* - World-leading'), ('3*', '3* - Internationally excellent'), ('2*', '2* - Recognized internationally'), ('1*', '1* - Recognized nationally'), ('U', 'Unclassified')], max_length=2)),
                ('comments', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('reviewed_date', models.DateTimeField(auto_now_add=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_reviews', to='core.output')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_date'],
            },
        ),
        migrations.CreateModel(
            name='CriticalFriendAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='assigned', max_length=20)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('quality_assessment', models.CharField(blank=True, choices=[('4*', '4* - World-leading'), ('3*', '3* - Internationally excellent'), ('2*', '2* - Recognized internationally'), ('1*', '1* - Recognized nationally'), ('U', 'Unclassified')], max_length=2)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('originality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('significance_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rigour_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('critical_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.criticalfriend')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_friend_reviews', to='core.output')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('output', 'critical_friend')},
            },
        ),
    ]
