# Generated by Django 4.2.7 on 2025-10-23 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalPanelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "Panel Chair"),
                            ("member", "Panel Member"),
                            ("specialist", "Subject Specialist"),
                            ("external_liaison", "External Liaison"),
                        ],
                        default="member",
                        max_length=100,
                    ),
                ),
                ("expertise_area", models.CharField(max_length=200)),
                ("appointed_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.colleague"
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Panel Member",
                "verbose_name_plural": "Internal Panel Members",
            },
        ),
        migrations.CreateModel(
            name="InternalPanelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(default=django.utils.timezone.now)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "rating_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4*", "4* - World-leading"),
                            ("3*", "3* - Internationally excellent"),
                            ("2*", "2* - Recognized internationally"),
                            ("1*", "1* - Recognized nationally"),
                            ("U", "Unclassified"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_panel_assignments",
                        to="core.output",
                    ),
                ),
                (
                    "panel_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.internalpanelmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Panel Assignment",
                "verbose_name_plural": "Internal Panel Assignments",
                "unique_together": {("output", "panel_member")},
            },
        ),
    ]
