# Generated by Django 4.2.7 on 2025-12-04 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_upgrade_to_v4"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputColleague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the main colleague for REF submission purposes?",
                    ),
                ),
                (
                    "author_position",
                    models.IntegerField(
                        default=1,
                        help_text="Position of this colleague in the author list",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "contribution_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of this colleague's contribution",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colleague_outputs",
                        to="core.colleague",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_colleagues",
                        to="core.output",
                    ),
                ),
            ],
            options={
                "verbose_name": "Output Colleague Association",
                "verbose_name_plural": "Output Colleague Associations",
                "ordering": ["-is_main", "author_position"],
                "unique_together": {("output", "colleague")},
            },
        ),
        migrations.AddField(
            model_name="output",
            name="colleagues",
            field=models.ManyToManyField(
                blank=True,
                help_text="All colleagues associated with this output",
                related_name="multi_outputs",
                through="core.OutputColleague",
                to="core.colleague",
            ),
        ),
    ]
