# Generated by Django 4.2.7 on 2025-10-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_internalpanelmember_internalpanelassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleague",
            name="employment_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date when employment ended (for former staff)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colleague",
            name="employment_status",
            field=models.CharField(
                choices=[("current", "Current Staff"), ("former", "Former Staff")],
                default="current",
                help_text="Whether this person is currently employed or a former staff member",
                max_length=10,
            ),
        ),
    ]
