# Generated by Django 4.2.7 on 2025-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleague",
            name="colleague_category",
            field=models.CharField(
                choices=[
                    ("employee", "Current Employee"),
                    ("former", "Former Employee"),
                    ("coauthor", "Co-author (External)"),
                    ("non-independent", "Non-independent Researcher"),
                ],
                default="employee",
                help_text="Category of colleague for REF purposes",
                max_length=20,
                verbose_name="Colleague Category",
            ),
        ),
    ]
