# Generated by Django 4.2.7 on 2025-10-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_colleague_colleague_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colleague",
            name="colleague_category",
            field=models.CharField(
                choices=[
                    ("independent", "Independent Researcher"),
                    ("non_independent", "Non-Independent Researcher"),
                    ("postdoc", "Post-Doctoral Researcher"),
                    ("research_assistant", "Research Assistant"),
                    ("academic", "Academic Staff"),
                    ("support", "Support Staff"),
                    ("employee", "Current Employee"),
                    ("former", "Former Employee"),
                    ("coauthor", "Co-author (External)"),
                    ("non-independent", "Non-independent Researcher"),
                ],
                default="independent",
                help_text="Category of colleague for REF purposes",
                max_length=50,
                verbose_name="Colleague Category",
            ),
        ),
    ]
