# Generated by Django 4.2.7 on 2025-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_criticalfriend_is_internal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="criticalfriend",
            old_name="added_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="criticalfriend",
            name="last_contacted",
        ),
        migrations.AddField(
            model_name="criticalfriend",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="criticalfriend",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("limited", "Limited Availability"),
                    ("unavailable", "Unavailable"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="criticalfriend",
            name="is_internal",
            field=models.BooleanField(
                default=False,
                help_text="Check if this reviewer is part of your internal panel (not an external critical friend)",
            ),
        ),
    ]
