# Generated by Django 4.2.7 on 2025-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_added_date_criticalfriend_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted for Review"),
                    ("internal-review", "Internal Review"),
                    ("external-review", "External Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revision", "Needs Revision"),
                    ("aside", "Set aside for now"),
                    ("planning", "In Planning"),
                    ("ready", "Ready to Submit"),
                    ("reserve", "Reserve"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
