# Generated by Django 4.2.7 on 2025-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_output_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="quality_rating_average",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4*", "4* - World-leading"),
                    ("3*", "3* - Internationally excellent"),
                    ("2*", "2* - Recognized internationally"),
                    ("1*", "1* - Recognized nationally"),
                    ("U", "Unclassified"),
                ],
                help_text="Calculated average of internal and external ratings",
                max_length=2,
                verbose_name="Average Rating",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="quality_rating_external",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4*", "4* - World-leading"),
                    ("3*", "3* - Internationally excellent"),
                    ("2*", "2* - Recognized internationally"),
                    ("1*", "1* - Recognized nationally"),
                    ("U", "Unclassified"),
                ],
                help_text="Quality assessment from critical friends",
                max_length=2,
                verbose_name="Critical Friend Rating",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="quality_rating_internal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4*", "4* - World-leading"),
                    ("3*", "3* - Internationally excellent"),
                    ("2*", "2* - Recognized internationally"),
                    ("1*", "1* - Recognized nationally"),
                    ("U", "Unclassified"),
                ],
                help_text="Quality assessment from internal panel",
                max_length=2,
                verbose_name="Internal Panel Rating",
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="quality_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4*", "4* - World-leading"),
                    ("3*", "3* - Internationally excellent"),
                    ("2*", "2* - Recognized internationally"),
                    ("1*", "1* - Recognized nationally"),
                    ("U", "Unclassified"),
                ],
                max_length=2,
                verbose_name="Overall Rating (Deprecated)",
            ),
        ),
    ]
