# Generated by Django 4.2.7 on 2025-11-18 10:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_output_quality_rating_average_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="REFSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this submission scenario (e.g., 'Main Submission v2', 'Conservative Strategy')",
                        max_length=200,
                    ),
                ),
                (
                    "uoa",
                    models.CharField(
                        help_text="Which UOA this submission is for (e.g., 'UOA 25 - Modern Languages')",
                        max_length=100,
                        verbose_name="Unit of Assessment",
                    ),
                ),
                (
                    "submission_year",
                    models.IntegerField(default=2029, help_text="REF submission year"),
                ),
                (
                    "portfolio_quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average quality score (GPA calculation)",
                        max_digits=4,
                    ),
                ),
                (
                    "portfolio_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Portfolio risk score (inverted: 1 = low risk, 0 = high risk)",
                        max_digits=4,
                    ),
                ),
                (
                    "representativeness_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="How well submission represents departmental research areas",
                        max_digits=4,
                    ),
                ),
                (
                    "equality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of eligible staff submitted (0-100)",
                        max_digits=4,
                    ),
                ),
                (
                    "gender_balance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gender balance metric (1 = perfect balance, 0 = severe imbalance)",
                        max_digits=4,
                    ),
                ),
                (
                    "ecr_representation_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Early Career Researcher representation score",
                        max_digits=4,
                    ),
                ),
                (
                    "interdisciplinary_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Proportion of interdisciplinary outputs",
                        max_digits=4,
                    ),
                ),
                (
                    "weight_quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.40"),
                        help_text="Weight for quality in portfolio score",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "weight_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.25"),
                        help_text="Weight for risk management in portfolio score",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "weight_representativeness",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.15"),
                        help_text="Weight for research area representation",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "weight_equality",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Weight for staff inclusion",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "weight_gender_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Weight for gender balance",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this submission strategy"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this an active submission scenario?"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Is this the final submission?"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this submission"
                    ),
                ),
                (
                    "metrics_last_calculated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When portfolio metrics were last calculated",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "REF Submission",
                "verbose_name_plural": "REF Submissions",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="output",
            name="content_risk_rationale",
            field=models.TextField(
                blank=True,
                help_text="Explain why this output might face panel disagreement or concerns",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="content_risk_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Risk of panel disagreement with methodology/approach (0-1 scale)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="interdisciplinary_flag",
            field=models.BooleanField(
                default=False,
                help_text="Is this interdisciplinary work? (May receive additional weighting)",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="oa_compliance_notes",
            field=models.TextField(
                blank=True, help_text="Details about OA compliance status or concerns"
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="oa_compliance_risk",
            field=models.BooleanField(
                default=False,
                help_text="Is there Open Access compliance risk? (Critical for REF)",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="overall_risk_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Calculated composite risk score",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="panel_alignment_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes on panel alignment concerns or alternative UOA considerations",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="panel_alignment_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="How well does this align with panel expertise? (1=perfect, 0=poor)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="risk_content_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.60"),
                help_text="Weight for content risk (default 0.6)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="risk_last_calculated",
            field=models.DateTimeField(
                blank=True, help_text="When risk scores were last calculated", null=True
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="risk_timeline_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.40"),
                help_text="Weight for timeline risk (default 0.4)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="timeline_risk_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Risk of publication delay (0=published, 1=planning stage)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="venue_prestige_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.50"),
                help_text="Journal/venue prestige and reputation (0=low, 1=high)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="SubmissionOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within submission"
                    ),
                ),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes specific to this output's inclusion in this submission",
                    ),
                ),
                (
                    "is_reserve",
                    models.BooleanField(
                        default=False, help_text="Is this a reserve/backup output?"
                    ),
                ),
                (
                    "strategic_importance",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("important", "Important"),
                            ("standard", "Standard"),
                            ("optional", "Optional"),
                        ],
                        default="standard",
                        help_text="Strategic importance of this output to the submission",
                        max_length=20,
                    ),
                ),
                ("included_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_inclusions",
                        to="core.output",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_outputs",
                        to="core.refsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Output",
                "verbose_name_plural": "Submission Outputs",
                "ordering": ["order", "included_date"],
                "unique_together": {("submission", "output")},
            },
        ),
        migrations.AddField(
            model_name="refsubmission",
            name="outputs",
            field=models.ManyToManyField(
                help_text="Outputs included in this submission",
                related_name="ref_submissions",
                through="core.SubmissionOutput",
                to="core.output",
            ),
        ),
    ]
