# Generated by Django 4.2.7 on 2025-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_refsubmission_output_content_risk_rationale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalpanelassignment",
            name="reviewer_type",
            field=models.CharField(
                choices=[
                    ("specialist", "Specialist"),
                    ("non-specialist", "Non-Specialist"),
                ],
                default="specialist",
                help_text="Is this panel member a specialist in this research area?",
                max_length=20,
                verbose_name="Reviewer Expertise Type",
            ),
        ),
        migrations.AddField(
            model_name="output",
            name="quality_rating_self",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4*", "4* - World-leading"),
                    ("3*", "3* - Internationally excellent"),
                    ("2*", "2* - Recognized internationally"),
                    ("1*", "1* - Recognized nationally"),
                    ("U", "Unclassified"),
                ],
                help_text="Author's own quality assessment",
                max_length=2,
                verbose_name="Self-Assessment Rating",
            ),
        ),
    ]
