# Generated by Django 4.2.7 on 2025-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_internalpanelassignment_reviewer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criticalfriendassignment",
            name="reviewer_type",
            field=models.CharField(
                choices=[
                    ("specialist", "Specialist"),
                    ("non-specialist", "Non-Specialist"),
                ],
                default="specialist",
                help_text="Is this critical friend a specialist in this research area?",
                max_length=20,
                verbose_name="Reviewer Expertise Type",
            ),
        ),
    ]
