# Generated by Django 4.2.7 on 2025-11-20 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_criticalfriendassignment_reviewer_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="output",
            options={
                "ordering": ["-publication_year"],
                "verbose_name_plural": "Outputs",
            },
        ),
        migrations.RemoveField(
            model_name="output",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="output",
            name="publication_year",
            field=models.IntegerField(
                default=2024,
                help_text="Year of publication (e.g., 2024)",
                validators=[
                    django.core.validators.MinValueValidator(2021),
                    django.core.validators.MaxValueValidator(2028),
                ],
            ),
            preserve_default=False,
        ),
    ]
