# Generated by Django 4.2.7 on 2025-11-27 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_alter_output_options_remove_output_publication_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("OBSERVER", "Observer (Read-Only)"),
                            ("INTERNAL_PANEL", "Internal Panel Member"),
                            ("COLLEAGUE", "Colleague"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "can_view_all_outputs",
                    models.BooleanField(
                        default=False, help_text="Can view all outputs in the system"
                    ),
                ),
                (
                    "can_view_all_colleagues",
                    models.BooleanField(
                        default=False, help_text="Can view all colleague records"
                    ),
                ),
                (
                    "can_view_all_ratings",
                    models.BooleanField(
                        default=False, help_text="Can view all internal ratings"
                    ),
                ),
                (
                    "can_edit_any_output",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit any output regardless of ownership",
                    ),
                ),
                (
                    "can_delete_any_output",
                    models.BooleanField(
                        default=False, help_text="Can delete any output"
                    ),
                ),
                (
                    "can_edit_any_rating",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit any rating including finalised ones",
                    ),
                ),
                (
                    "can_create_outputs",
                    models.BooleanField(
                        default=False, help_text="Can create new outputs"
                    ),
                ),
                (
                    "can_rate_assigned",
                    models.BooleanField(
                        default=False,
                        help_text="Can rate outputs assigned to this user",
                    ),
                ),
                (
                    "can_unfinalise_ratings",
                    models.BooleanField(
                        default=False,
                        help_text="Can un-finalise ratings that have been locked",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, help_text="Can manage user accounts and roles"
                    ),
                ),
                (
                    "can_assign_panel",
                    models.BooleanField(
                        default=False, help_text="Can assign outputs to panel members"
                    ),
                ),
                (
                    "can_export_data",
                    models.BooleanField(
                        default=False, help_text="Can export data from the system"
                    ),
                ),
                (
                    "can_import_data",
                    models.BooleanField(
                        default=False, help_text="Can import data into the system"
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linked_colleague",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Colleague record for this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="core.colleague",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User can have multiple roles. Permissions are combined.",
                        related_name="users",
                        to="core.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="PanelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_assignments",
                        to="core.output",
                    ),
                ),
                (
                    "panel_member",
                    models.ForeignKey(
                        limit_choices_to={"roles__code": "INTERNAL_PANEL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel Assignment",
                "verbose_name_plural": "Panel Assignments",
                "ordering": ["-assigned_date"],
                "unique_together": {("output", "panel_member")},
            },
        ),
        migrations.CreateModel(
            name="InternalRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Not Rated"),
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Justification and notes for this rating"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Once finalised, only admins can modify",
                    ),
                ),
                (
                    "finalised_date",
                    models.DateTimeField(
                        blank=True, help_text="When the rating was finalised", null=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_ratings",
                        to="core.output",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Rating",
                "verbose_name_plural": "Internal Ratings",
                "ordering": ["-created_date"],
                "unique_together": {("output", "rater")},
            },
        ),
    ]
