# Generated by Django 4.2.7 on 2025-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_three_component_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalpanelassignment",
            name="component_average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated average of O/S/R",
                max_digits=3,
                null=True,
                verbose_name="Average Rating",
            ),
        ),
        migrations.AddField(
            model_name="internalpanelassignment",
            name="confidential_comments",
            field=models.TextField(
                blank=True,
                help_text="Visible only to administrators, observers, and panel members",
                verbose_name="Confidential Comments",
            ),
        ),
        migrations.AddField(
            model_name="internalpanelassignment",
            name="originality_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate originality from 0.00 to 4.00",
                max_digits=3,
                null=True,
                verbose_name="Originality",
            ),
        ),
        migrations.AddField(
            model_name="internalpanelassignment",
            name="rigour_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate rigour from 0.00 to 4.00",
                max_digits=3,
                null=True,
                verbose_name="Rigour",
            ),
        ),
        migrations.AddField(
            model_name="internalpanelassignment",
            name="significance_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate significance from 0.00 to 4.00",
                max_digits=3,
                null=True,
                verbose_name="Significance",
            ),
        ),
    ]
